[tool.poetry]
name = "aposteriori"
version = "0.1.0"
description = "DNN based protein design."
authors = ["Chris Wells Wood <cwwoodesq@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/wells-wood-research/aposteriori"
homepage = "https://github.com/wells-wood-research/aposteriori"

[tool.poetry.dependencies]
python = "^3.7"
AMPAL = "^1.4"
Cython = "^0.29.6"
numpy = "^1.16"
scikit-learn = "^0.20.3"
h5py = "^2.9"
tensorflow = "^1.13"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
jupyter = "^1.0"
matplotlib = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
